/*
 * Ranged Weapons Mod - guns for players, on the Ranged Weapons protocol.
 * Copyright (C) 2026 Rusty Shackleford and nfx
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package com.nfx.rangedweaponsmod.gametest;

import net.minecraft.world.item.Item;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.List;

/**
 * The gametest mod's own entry point: registers the photo booth's
 * calibration items -- the gun's model under six candidate display
 * transforms, generated by {@code devtools/art/build.py booth} -- so one
 * booth run photographs them all. Never shipped.
 */
@Mod(BoothMod.MOD_ID)
public final class BoothMod {
    public static final String MOD_ID = "rangedweaponsmod_gametest";

    private static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MOD_ID);

    /** One item per candidate, named a..f as in the generator. */
    public static final List<DeferredItem<Item>> BOOTH_ITEMS = List.of(
            ITEMS.registerItem("booth_a", Item::new, new Item.Properties()),
            ITEMS.registerItem("booth_b", Item::new, new Item.Properties()),
            ITEMS.registerItem("booth_c", Item::new, new Item.Properties()),
            ITEMS.registerItem("booth_d", Item::new, new Item.Properties()),
            ITEMS.registerItem("booth_e", Item::new, new Item.Properties()),
            ITEMS.registerItem("booth_f", Item::new, new Item.Properties()));

    public BoothMod(IEventBus modBus) {
        ITEMS.register(modBus);
    }
}
