"""Reproducible launcher geometry and sixteen-pixel parts, in the gun atlas palette.

Copyright 2026 Rusty Shackleford and nfx. AGPL-3.0-or-later.
"""

import json
import struct
import zlib
from pathlib import Path
from typing import TypeAlias

from material_bevel import Pixel, bevel

Json: TypeAlias = str | int | float | bool | None | list["Json"] | dict[str, "Json"]
Vec: TypeAlias = tuple[float, float, float]
ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "src/main/resources/assets/rangedweaponsmod"
CREDIT = (
    "Rusty Shackleford and nfx; original art generated by devtools/art/launcher_art.py"
)
CELLS = {
    "metal_mid": (0, 0),
    "metal_dark": (1, 0),
    "metal_light": (2, 0),
    "barrel": (3, 0),
    "wood": (0, 1),
    "wood_dark": (1, 1),
    "brass": (2, 1),
    "vent": (3, 1),
    "receiver": (0, 2),
    "grip": (1, 2),
    "magazine": (2, 2),
    "muzzle": (3, 2),
}
DIRECTIONS = ("north", "south", "east", "west", "up", "down")


def _box(
    name: str, lo: Vec, hi: Vec, material: str, top: str | None = None
) -> dict[str, Json]:
    faces: dict[str, Json] = {}
    for face in DIRECTIONS:
        cell = top if top and face == "up" else material
        x, y = CELLS[cell]
        faces[face] = {"texture": "#gun", "uv": [x * 4, y * 4, x * 4 + 4, y * 4 + 4]}
    return {"name": name, "from": list(lo), "to": list(hi), "faces": faces}


def _model(elements: list[dict[str, Json]]) -> dict[str, Json]:
    return {
        "credit": CREDIT,
        "texture_size": [32, 32],
        "textures": {
            "gun": "rangedweaponsmod:item/gun_atlas",
            "particle": "rangedweaponsmod:item/gun_atlas",
        },
        "elements": list(elements),
    }


def _launcher() -> dict[str, Json]:
    b = _box
    pieces = [
        b("tube_main", (-10, 9, 5.5), (27, 13, 10.5), "metal_mid"),
        b("tube_top_plane", (-10, 13, 6), (27, 13.5, 10), "metal_mid", "metal_light"),
        b("tube_bottom_plane", (-10, 8.5, 6), (27, 9, 10), "metal_dark"),
        b("wood_shoulder_rest", (-8, 6.5, 6), (-1, 8.5, 10), "wood_dark", "wood"),
        b("shoulder_pad", (-9, 6, 5.8), (-7.5, 8.8, 10.2), "grip"),
        b("lower_receiver", (0, 7, 6.6), (9, 8.5, 9.4), "receiver", "metal_mid"),
        b("grip", (1, 2, 7), (3.5, 7, 9), "grip", "wood"),
        b("grip_heel", (0.8, 1.5, 6.8), (3.7, 2.3, 9.2), "wood_dark"),
        b("trigger_guard_bottom", (3.5, 4.8, 7.5), (7, 5.4, 8.5), "metal_dark"),
        b("trigger_guard_front", (6.4, 4.8, 7.5), (7, 7, 8.5), "metal_dark"),
        b("trigger", (4.3, 5.4, 7.7), (4.9, 7, 8.3), "brass"),
        b("foregrip_mount", (12, 7.3, 6.5), (18, 8.5, 9.5), "metal_dark"),
        b("wood_foregrip", (13.3, 3.5, 7), (16, 7.3, 9), "wood_dark", "wood"),
        b("seeker_mount_back", (7.5, 13.5, 7), (9, 14.5, 9), "metal_dark"),
        b("seeker_mount_front", (14, 13.5, 7), (15.5, 14.5, 9), "metal_dark"),
        b("seeker_housing", (7, 14.5, 6.4), (16, 17, 9.6), "receiver", "metal_mid"),
        b("seeker_top", (7.5, 17, 6.7), (15.5, 17.4, 9.3), "metal_light"),
        b("seeker_eye_cup", (5.8, 14.8, 6.8), (7, 16.7, 9.2), "barrel"),
        b("seeker_rear_glass", (5.7, 15.2, 7.2), (5.8, 16.3, 8.8), "metal_light"),
        b("seeker_front_glass", (16, 15, 7), (16.1, 16.5, 9), "metal_light"),
        b("seeker_front_hood_top", (15.8, 16.5, 6.5), (17, 17.1, 9.5), "metal_dark"),
        b("seeker_front_hood_bottom", (15.8, 14.4, 6.5), (17, 15, 9.5), "metal_dark"),
        b("seeker_front_hood_left", (15.8, 15, 6.5), (17, 16.5, 7), "metal_dark"),
        b("seeker_front_hood_right", (15.8, 15, 9), (17, 16.5, 9.5), "metal_dark"),
        b("seeker_dial", (10, 15, 9.6), (11.5, 16.5, 10.1), "brass"),
        b("seeker_switch", (12.5, 15, 9.6), (14, 15.6, 10), "barrel"),
        b("rear_latch", (-3, 11, 10.5), (0, 12, 11), "metal_light"),
    ]
    # Four walls around each opening expose a recessed dark bore, not a painted cap.
    for label, x0, x1 in [
        ("muzzle", 27, 30),
        ("breech", -12, -10),
        ("rear_band", -5, -3.5),
        ("front_band", 20.5, 22),
    ]:
        pieces.extend(
            [
                b(
                    label + "_top",
                    (x0, 13, 5.2),
                    (x1, 14, 10.8),
                    "metal_mid",
                    "metal_light",
                ),
                b(label + "_bottom", (x0, 8, 5.2), (x1, 9, 10.8), "metal_dark"),
                b(label + "_left", (x0, 9, 5.2), (x1, 13, 6.2), "metal_mid"),
                b(label + "_right", (x0, 9, 9.8), (x1, 13, 10.8), "metal_mid"),
            ]
        )
    pieces += [
        b("muzzle_bore", (26.9, 9, 6.2), (27.01, 13, 9.8), "barrel"),
        b("breech_bore", (-10.01, 9, 6.2), (-9.9, 13, 9.8), "barrel"),
    ]
    model = _model(pieces)
    # Retained after shader photographs: both fists meet the grips, the muzzle
    # clears the hands, the scope clears the reticle, and the icon fits its slot.
    model["display"] = {
        "firstperson_righthand": {
            "rotation": [0, 92, 0],
            "translation": [1, 0.5, -3],
            "scale": [0.5, 0.5, 0.5],
        },
        "thirdperson_righthand": {
            "rotation": [0, 90, 0],
            "translation": [0, 1.5, 1],
            "scale": [0.55, 0.55, 0.55],
        },
        "gui": {
            "rotation": [0, 0, 0],
            "translation": [-0.4, 0, 0],
            "scale": [0.36, 0.36, 0.36],
        },
        "ground": {
            "rotation": [0, 0, 0],
            "translation": [0, 2, 0],
            "scale": [0.3, 0.3, 0.3],
        },
        "fixed": {
            "rotation": [0, 0, 0],
            "translation": [-0.4, 0, 0],
            "scale": [0.36, 0.36, 0.36],
        },
    }
    return model


def _rocket() -> dict[str, Json]:
    b = _box
    # Exactly centred on (8,8,8); 22 pixels nose to exhaust; +Z is forward.
    return _model(
        [
            b(
                "motor_casing",
                (6.5, 6.5, -2),
                (9.5, 9.5, 8),
                "metal_mid",
                "metal_light",
            ),
            b("warhead", (6.3, 6.3, 8), (9.7, 9.7, 14), "metal_light"),
            b("warhead_band", (6.2, 6.2, 9), (9.8, 9.8, 10), "brass"),
            b("nose_shoulder", (6.6, 6.6, 14), (9.4, 9.4, 16), "metal_dark"),
            b("nose", (7, 7, 16), (9, 9, 18), "barrel"),
            b("nose_tip", (7.5, 7.5, 18), (8.5, 8.5, 19), "barrel"),
            b("exhaust_collar_top", (6.4, 9, -3), (9.6, 9.6, -1.5), "metal_dark"),
            b("exhaust_collar_bottom", (6.4, 6.4, -3), (9.6, 7, -1.5), "metal_dark"),
            b("exhaust_collar_left", (6.4, 7, -3), (7, 9, -1.5), "metal_dark"),
            b("exhaust_collar_right", (9, 7, -3), (9.6, 9, -1.5), "metal_dark"),
            b("exhaust_bore", (7, 7, -2.5), (9, 9, -2.4), "barrel"),
            b("fin_top", (7.75, 9.4, -2.5), (8.25, 11, 2.5), "metal_light"),
            b("fin_bottom", (7.75, 5, -2.5), (8.25, 6.6, 2.5), "metal_mid"),
            b("fin_left", (5, 7.75, -2.5), (6.6, 8.25, 2.5), "metal_mid"),
            b("fin_right", (9.4, 7.75, -2.5), (11, 8.25, 2.5), "metal_light"),
        ]
    )


# Authored rows are deliberately small enough to judge beside barrel/scope at 16 px.
PALETTE: dict[str, Pixel] = {
    ".": (0, 0, 0, 0),
    "d": (28, 30, 34, 255),
    "s": (74, 80, 90, 255),
    "l": (118, 126, 140, 255),
    "h": (165, 171, 180, 255),
    "g": (176, 141, 60, 255),
    "w": (120, 82, 44, 255),
    "c": (76, 120, 128, 255),
}
ICONS = {
    "rocket": (
        "................",
        ".......dd.......",
        "......dssd......",
        "......slhs......",
        "......slhs......",
        "......sggs......",
        "......slhs......",
        "......slhs......",
        "......slhs......",
        "......slhs......",
        ".....sslhsd.....",
        "....lsslhsds....",
        "....lsslhsds....",
        "....lsddddds....",
        "......sdds......",
        "................",
    ),
    "launch_tube": (
        "................",
        "..........llll..",
        ".........lssddl.",
        "........lssdddl.",
        ".......lsssddl..",
        "......lssssl....",
        ".....lsssdl.....",
        "....lsssdl......",
        "...lsssdl.......",
        "..lsssdl........",
        ".lsssdl.........",
        ".lssdl..........",
        ".sddl...........",
        "..dl............",
        "................",
        "................",
    ),
    "seeker": (
        "................",
        "................",
        "....lllllll.....",
        "...lsssssssl....",
        "..dlssssssssl...",
        "..dslssssssdcd..",
        "..dslsggsssdcdd.",
        "..dslsggsssdcdd.",
        "..dslssssssdcd..",
        "...dsssssssd....",
        "....ddddddd.....",
        ".....ss.ss......",
        ".....dd.dd......",
        "................",
        "................",
        "................",
    ),
}


def _png(path: Path, rows: tuple[tuple[Pixel, ...], ...]) -> None:
    raw = b"".join(b"\0" + b"".join(bytes(p) for p in row) for row in rows)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", 16, 16, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def generate(want: set[str]) -> None:
    """requires: repository resource directories exist; want names textures/model.

    effects: regenerates only launcher models and part icons. throws: OSError on I/O failure.
    """
    if "model" in want:
        models = {"rocket_launcher": _launcher(), "rocket_projectile": _rocket()}
        for name in ICONS:
            models[name] = {
                "credit": CREDIT,
                "parent": "minecraft:item/generated",
                "textures": {"layer0": f"rangedweaponsmod:item/{name}"},
            }
        for name, model in models.items():
            (ASSETS / f"models/item/{name}.json").write_text(
                json.dumps(model, indent=2) + "\n"
            )
    if "textures" in want:
        for name, rows in ICONS.items():
            _png(
                ASSETS / f"textures/item/{name}.png",
                bevel([[PALETTE[c] for c in row] for row in rows]),
            )


if __name__ == "__main__":
    generate({"textures", "model"})
