"""The weapons workbench and the lock-on chip (D-0029), as code: the bench's faces, its screen,
the chip's icon, the fitting slots' empty icons, and the block's models and states.

Copyright 2026 Rusty Shackleford and nfx. AGPL-3.0-or-later.

Original work in vanilla's family: the smithing table's dark iron frame around a wooden panel with
tools hung on it, here a dark walnut panel with a rifle and a pistol on its front, a wrench and a
shelf of brass rounds on its sides, and a steel top scribed with the three-by-three grid it
assembles on. The panel is dark so the steel on it reads: steel and a mid walnut have one
luminance, and the first draft's tools vanished into it. Run through
build.py (`uv run --no-project python devtools/art/build.py textures model`), or alone.
"""

import json
import struct
import zlib
from pathlib import Path

from material_bevel import bevel

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "src/main/resources/assets/rangedweaponsmod"
DATA = ROOT / "src/main/resources/data"
CREDIT = "Rusty Shackleford and nfx; original art generated by devtools/art/workbench_art.py"

type Pixel = tuple[int, int, int, int]

# The bench's colours: the smithing table's irons, the gun atlas's steel, a walnut like the stocks.
PALETTE: dict[str, tuple[int, int, int]] = {
    "K": (17, 18, 19),     # iron, deepest
    "I": (26, 27, 30),     # iron band
    "i": (38, 39, 45),     # iron band, lit
    "j": (47, 48, 55),     # iron band, highlight
    "D": (43, 47, 54),     # steel, dark
    "s": (60, 65, 74),     # steel, shade
    "S": (74, 80, 90),     # steel
    "L": (118, 126, 140),  # steel, light
    "T": (150, 158, 172),  # steel, glint
    "W": (84, 56, 32),     # walnut: dark, so steel hung on it reads (the smithing table's panel is darker still)
    "w": (72, 48, 27),     # walnut, grain
    "v": (60, 40, 23),     # walnut, dark
    "V": (42, 28, 16),     # walnut, seam
    "b": (28, 30, 34),     # barrel
    "o": (139, 94, 52),    # stock
    "O": (101, 68, 38),    # stock, dark
    "g": (214, 180, 96),   # brass, lit
    "G": (176, 141, 60),   # brass
    "H": (128, 98, 38),    # brass, dark
    "c": (222, 140, 90),   # copper tip, lit
    "C": (184, 100, 52),   # copper tip
}

# Where the screen's slots stand: WorkbenchMenu's numbers, to the pixel.
GRID_X, GRID_Y = 12, 17
RESULT_X, RESULT_Y = 102, 35
WEAPON_X, WEAPON_Y = 146, 21
CHIP_X, CHIP_Y = 146, 49
FRAME_U, FRAME_V = 176, 0


def write_png(path: Path, width: int, height: int, rows) -> None:
    """rows: rows of (r, g, b, a), top row first."""
    raw = b"".join(b"\x00" + b"".join(bytes(p) for p in row) for row in rows)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"\x89PNG\r\n\x1a\n"
                     + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
                     + chunk(b"IDAT", zlib.compress(raw, 9))
                     + chunk(b"IEND", b""))


class Grain:
    """A deterministic grain, so flat colours read as material."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next(self) -> float:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state / 0xFFFFFFFF


def _shade(rgb, delta):
    return tuple(max(0, min(255, c + delta)) for c in rgb)


def _grid(rows: list[str]) -> list[list[Pixel]]:
    """effects: a 16 by 16 raster from character rows; '.' is transparent."""
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), rows
    return [[(0, 0, 0, 0) if c == "." else (*PALETTE[c], 255) for c in row] for row in rows]


def _over(base: list[list[Pixel]], rows: list[str], x0: int = 0, y0: int = 0) -> None:
    """effects: paints the characters of {@code rows} over {@code base} from (x0, y0); '.' leaves it."""
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            if c != "." and 0 <= y0 + y < 16 and 0 <= x0 + x < 16:
                base[y0 + y][x0 + x] = (*PALETTE[c], 255)


def _walnut(seed: int) -> list[list[Pixel]]:
    """effects: a walnut panel of horizontal boards, four pixels deep with a seam between, grained."""
    g = Grain(seed)
    px: list[list[Pixel]] = []
    for y in range(16):
        row: list[Pixel] = []
        for x in range(16):
            if y % 4 == 3:
                c = PALETTE["V"]
            else:
                c = PALETTE["W"] if (x + 3 * (y // 4)) % 7 not in (0, 4) else PALETTE["w"]
                c = _shade(c, int(g.next() * 7) - 3)
            row.append((*c, 255))
        px.append(row)
    return px


def _framed(panel: list[list[Pixel]], band: int) -> list[list[Pixel]]:
    """effects: the smithing table's frame round {@code panel}: an iron band {@code band} deep along
    the top, two-pixel posts at the sides, one row at the bottom, darkest at the corners."""
    px = [row[:] for row in panel]
    for y in range(16):
        for x in range(16):
            top = y < band
            post = x < 2 or x > 13
            bottom = y == 15
            if top or post or bottom:
                if (x in (0, 15)) or y == 0 or bottom:
                    c = PALETTE["I"]
                elif top and y == band - 1:
                    c = PALETTE["K"]
                elif x in (1, 14) and not top:
                    c = PALETTE["i"]
                else:
                    c = PALETTE["j"] if y == 1 else PALETTE["i"]
                px[y][x] = (*c, 255)
    for x, y in ((0, 0), (15, 0), (0, 15), (15, 15)):
        px[y][x] = (*PALETTE["K"], 255)
    return px


def front() -> list[list[Pixel]]:
    """The front: a rifle on two pegs over a pistol, in the walnut frame."""
    px = _framed(_walnut(41), band=3)
    _over(px, [
        "..i......i..",
        ".....TT....T",
        "VoooLLLLLLLL",
        "VooOSSSs....",
        "V....sD.....",
        "......D.....",
    ], 2, 3)
    _over(px, [
        "..LLLLLT",
        "..LSs...",
        "..SO....",
        "..O.....",
    ], 3, 10)
    return px


def side() -> list[list[Pixel]]:
    """The sides: a wrench on a peg, and three brass rounds standing on a shelf, in the walnut frame."""
    px = _framed(_walnut(97), band=3)
    _over(px, [
        ".i.",
        "T.T",
        "LTL",
        ".L.",
        ".L.",
        ".L.",
        ".L.",
        "LsL",
        "L.L",
    ], 2, 3)
    _over(px, [
        "..c..c..c",
        ".cC.cC.cC",
        ".gG.gG.gG",
        ".gG.gG.gG",
        ".gH.gH.gH",
        ".HH.HH.HH",
        "iiiiiiiii",
    ], 5, 6)
    return px


def top() -> list[list[Pixel]]:
    """The top: a steel plate in an iron rim, bolted at the corners, scribed with the 3x3 grid."""
    g = Grain(7)
    px: list[list[Pixel]] = []
    for y in range(16):
        row: list[Pixel] = []
        for x in range(16):
            if x in (0, 15) or y in (0, 15):
                c = PALETTE["I"]
            elif x in (1, 14) or y in (1, 14):
                c = PALETTE["i"]
            else:
                c = _shade(PALETTE["S"], int(g.next() * 15) - 9)
            row.append((*c, 255))
        px.append(row)
    # The scribed grid: three cells of three, lines in the plate's shade, a lit edge below each.
    for k in (3, 6, 9, 12):
        for t in range(3, 13):
            px[k][t] = (*PALETTE["D"], 255)
            px[t][k] = (*PALETTE["D"], 255)
    for x, y in ((2, 2), (13, 2), (2, 13), (13, 13)):
        px[y][x] = (*PALETTE["T"], 255)
        if y + 1 < 15 and x + 1 < 15:
            px[y + 1][x + 1] = (*PALETTE["D"], 255)
    return px


def bottom() -> list[list[Pixel]]:
    """The bottom: dark walnut boards in an iron rim."""
    px = _walnut(13)
    for y in range(16):
        for x in range(16):
            px[y][x] = (*_shade(px[y][x][:3], -28), 255)
            if x in (0, 15) or y in (0, 15):
                px[y][x] = (*PALETTE["I"], 255)
    return px


# The chip: a comparator-dark die on a quartz board, redstone traces, gold fingers.
CHIP_PALETTE = {
    "q": (232, 226, 216), "Q": (204, 196, 184), "k": (40, 40, 46), "K": (66, 66, 74),
    "g": (250, 210, 64), "G": (192, 146, 34), "r": (176, 30, 24), "R": (240, 64, 46),
}
CHIP = [
    "................",
    "................",
    "................",
    "..QqqqqqqqqqqQ..",
    "..qqqqqqqqqqqQ..",
    "..qqKkkkkkkKqQ..",
    "..qqkkkkkkkkqQ..",
    "..qqkkkRkkkkqQ..",
    "..qqkkkkkkkkqQ..",
    "..qqKkkkkkkKqQ..",
    "..qqqrqrqqrqqQ..",
    "..qqqrqrqqrqqQ..",
    "..QgQgQgQgQgQQ..",
    "...G.G.G.G.G....",
    "................",
    "................",
]

# The fitting slots' empty icons, in vanilla's own grey: a launcher, and a chip.
GHOST = (85, 85, 85, 255)
EMPTY_LAUNCHER = [
    "................",
    "................",
    "................",
    "................",
    "......##........",
    "##############..",
    "###############.",
    "###############.",
    "##############..",
    "...##....##.....",
    "...##....##.....",
    "....#...........",
    "................",
    "................",
    "................",
    "................",
]
EMPTY_CHIP = [
    "................",
    "................",
    "...#.#.#.#.#....",
    "..###########...",
    "..#.........#...",
    ".##..#####..##..",
    "..#..#####..#...",
    ".##..#####..##..",
    "..#..#####..#...",
    "..#.........#...",
    "..###########...",
    "...#.#.#.#.#....",
    "................",
    "................",
    "................",
    "................",
]


def chip_icon():
    return bevel([[(0, 0, 0, 0) if c == "." else (*CHIP_PALETTE[c], 255) for c in row] for row in CHIP])


def ghost(rows):
    return [[(0, 0, 0, 0) if c == "." else GHOST for c in row] for row in rows]


def gui():
    """The bench's screen, 256x256: the 176x166 panel at the top left in the game's own idiom --
    the grey bevelled panel, the grid, the arrow, the result's big frame, the weapon slot with a
    small arrow up to where the chip slot opens, the inventory -- and beside it at (176, 0) the
    chip slot's frame, drawn by the screen only while that slot is open."""
    size, w, h = 256, 176, 166
    px = [[(0, 0, 0, 0) for _ in range(size)] for _ in range(size)]

    def put(x, y, c):
        px[y][x] = (*c, 255)

    panel, light, dark, black, well, edge = (198, 198, 198), (255, 255, 255), (85, 85, 85), (0, 0, 0), (139, 139, 139), (55, 55, 55)
    for y in range(h):
        for x in range(w):
            corner = (x < 3 and y < 3) or (x >= w - 3 and y >= h - 3) or (x < 3 and y >= h - 3) or (x >= w - 3 and y < 3)
            if corner and ((x in (0, w - 1) and y in (0, 1, h - 2, h - 1)) or (y in (0, h - 1) and x in (0, 1, w - 2, w - 1))):
                continue
            if x == 0 or y == 0 or x == w - 1 or y == h - 1:
                put(x, y, black)
            elif x <= 2 or y <= 2:
                put(x, y, light)
            elif x >= w - 3 or y >= h - 3:
                put(x, y, dark)
            else:
                put(x, y, panel)

    def slot(x, y, ox=0, oy=0):
        # An 18x18 sunken square around an item at (x, y): dark top-left edges, light bottom-right.
        for yy in range(y - 1, y + 17):
            for xx in range(x - 1, x + 17):
                if yy == y - 1 or xx == x - 1:
                    put(xx + ox, yy + oy, edge)
                elif yy == y + 16 or xx == x + 16:
                    put(xx + ox, yy + oy, light)
                else:
                    put(xx + ox, yy + oy, well)
        put(x + 16 + ox, y - 1 + oy, panel)
        put(x - 1 + ox, y + 16 + oy, panel)

    def big_slot(x, y):
        # The result's 26x26 frame, the crafting table's: an item at (x, y) sits in its middle.
        x0, y0 = x - 5, y - 5
        for yy in range(y0, y0 + 26):
            for xx in range(x0, x0 + 26):
                if yy == y0 or xx == x0:
                    put(xx, yy, edge)
                elif yy == y0 + 25 or xx == x0 + 25:
                    put(xx, yy, light)
                else:
                    put(xx, yy, well)
        put(x0 + 25, y0, well)
        put(x0, y0 + 25, well)

    def arrow(x, y):
        # The crafting table's arrow, 22 wide and 15 high: a head widening to its tip at the right,
        # a shaft three rows deep.
        for r in range(15):
            head = r + 1 if r <= 7 else 15 - r
            for k in range(head):
                put(x + 14 + k, y + r, well)
        for r, length in ((6, 21), (7, 22), (8, 21)):
            for k in range(length):
                put(x + k, y + r, well)

    for row in range(3):
        for col in range(3):
            slot(GRID_X + 18 * col, GRID_Y + 18 * row)
    arrow(GRID_X + 54 + 5, RESULT_Y)
    big_slot(RESULT_X, RESULT_Y)
    slot(WEAPON_X, WEAPON_Y)
    # A small arrow up from the chip's place to the weapon: the chip goes into it.
    mid = WEAPON_X + 8
    for r in range(4):
        for k in range(-r, r + 1):
            put(mid + k, WEAPON_Y + 19 + r, well)
    for r in range(4, 8):
        put(mid, WEAPON_Y + 19 + r, well)
        put(mid - 1, WEAPON_Y + 19 + r, well)
    for row in range(3):
        for col in range(9):
            slot(8 + 18 * col, 84 + 18 * row)
    for col in range(9):
        slot(8 + 18 * col, 142)
    # The chip slot's frame, kept beside the panel.
    slot(FRAME_U + 1, FRAME_V + 1)
    return px


def models() -> dict[Path, dict]:
    block = {
        "credit": CREDIT,
        "parent": "minecraft:block/cube",
        "textures": {
            "particle": "rangedweaponsmod:block/weapons_workbench_front",
            "north": "rangedweaponsmod:block/weapons_workbench_front",
            "south": "rangedweaponsmod:block/weapons_workbench_side",
            "east": "rangedweaponsmod:block/weapons_workbench_side",
            "west": "rangedweaponsmod:block/weapons_workbench_side",
            "up": "rangedweaponsmod:block/weapons_workbench_top",
            "down": "rangedweaponsmod:block/weapons_workbench_bottom",
        },
    }
    state = {"variants": {
        "facing=north": {"model": "rangedweaponsmod:block/weapons_workbench"},
        "facing=east": {"model": "rangedweaponsmod:block/weapons_workbench", "y": 90},
        "facing=south": {"model": "rangedweaponsmod:block/weapons_workbench", "y": 180},
        "facing=west": {"model": "rangedweaponsmod:block/weapons_workbench", "y": 270},
    }}
    return {
        ASSETS / "models/block/weapons_workbench.json": block,
        ASSETS / "blockstates/weapons_workbench.json": state,
        ASSETS / "models/item/weapons_workbench.json": {"parent": "rangedweaponsmod:block/weapons_workbench"},
        ASSETS / "models/item/lock_on_chip.json": {
            "credit": CREDIT, "parent": "minecraft:item/generated",
            "textures": {"layer0": "rangedweaponsmod:item/lock_on_chip"}},
    }


def generate(want: set[str]) -> None:
    """requires: run from anywhere; want names textures and/or model.
    effects: writes the bench's and the chip's textures, models and block states. throws: OSError."""
    if "textures" in want:
        faces = {"top": top(), "front": front(), "side": side(), "bottom": bottom()}
        for name, raster in faces.items():
            write_png(ASSETS / f"textures/block/weapons_workbench_{name}.png", 16, 16, raster)
        write_png(ASSETS / "textures/item/lock_on_chip.png", 16, 16, chip_icon())
        write_png(ASSETS / "textures/item/empty_slot_launcher.png", 16, 16, ghost(EMPTY_LAUNCHER))
        write_png(ASSETS / "textures/item/empty_slot_chip.png", 16, 16, ghost(EMPTY_CHIP))
        write_png(ASSETS / "textures/gui/workbench.png", 256, 256, gui())
        print("textures: weapons_workbench_{top,front,side,bottom}.png, lock_on_chip.png, empty_slot_{launcher,chip}.png, gui/workbench.png")
    if "model" in want:
        for path, model in models().items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(model, indent=2) + "\n")
        print("model: weapons_workbench (block, item, state), lock_on_chip")


if __name__ == "__main__":
    generate({"textures", "model"})
